/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as SportRouteImport } from './routes/sport'
import { Route as ScienceRouteImport } from './routes/science'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ArticleTitleRouteImport } from './routes/$articleTitle'
import { Route as IndexRouteImport } from './routes/index'

const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const SportRoute = SportRouteImport.update({
  id: '/sport',
  path: '/sport',
  getParentRoute: () => rootRouteImport,
} as any)
const ScienceRoute = ScienceRouteImport.update({
  id: '/science',
  path: '/science',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleTitleRoute = ArticleTitleRouteImport.update({
  id: '/$articleTitle',
  path: '/$articleTitle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$articleTitle': typeof ArticleTitleRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/science': typeof ScienceRoute
  '/sport': typeof SportRoute
  '/technology': typeof TechnologyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$articleTitle': typeof ArticleTitleRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/science': typeof ScienceRoute
  '/sport': typeof SportRoute
  '/technology': typeof TechnologyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$articleTitle': typeof ArticleTitleRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/science': typeof ScienceRoute
  '/sport': typeof SportRoute
  '/technology': typeof TechnologyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$articleTitle'
    | '/login'
    | '/profile'
    | '/register'
    | '/science'
    | '/sport'
    | '/technology'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$articleTitle'
    | '/login'
    | '/profile'
    | '/register'
    | '/science'
    | '/sport'
    | '/technology'
  id:
    | '__root__'
    | '/'
    | '/$articleTitle'
    | '/login'
    | '/profile'
    | '/register'
    | '/science'
    | '/sport'
    | '/technology'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticleTitleRoute: typeof ArticleTitleRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ScienceRoute: typeof ScienceRoute
  SportRoute: typeof SportRoute
  TechnologyRoute: typeof TechnologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sport': {
      id: '/sport'
      path: '/sport'
      fullPath: '/sport'
      preLoaderRoute: typeof SportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/science': {
      id: '/science'
      path: '/science'
      fullPath: '/science'
      preLoaderRoute: typeof ScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$articleTitle': {
      id: '/$articleTitle'
      path: '/$articleTitle'
      fullPath: '/$articleTitle'
      preLoaderRoute: typeof ArticleTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticleTitleRoute: ArticleTitleRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ScienceRoute: ScienceRoute,
  SportRoute: SportRoute,
  TechnologyRoute: TechnologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
